platform :ios, '12.0'
use_frameworks!

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end

target 'covi-pod-test_Example' do
  pod 'covi-pod-test', :path => '../'
  pod 'SwiftyXMLParser', '~> 5.3.0'
  pod 'Alamofire', '~> 5.4'
  pod 'SDWebImage', '~> 5.0'
  pod 'Player', '~> 0.13.2'
end